version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_RANDOM_ROOT_PASSWORD=1
#      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
  postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"